
spring:
  application.name: rabbit-consumer
  main.web-application-type: none
  rabbitmq:
    addresses: localhost:5672,localhost:6672
    username: admin
    password: admin
    custom:
     api-addresses: localhost:8080,localhost:8081

---
spring:
  profiles: stage
  rabbitmq:
    addresses: P4-IO-PSH-MQ-1.infobip.local:5672,P4-IO-PSH-MQ-2.infobip.local:5672
    custom:
      api-addresses:
